# openapi: 3.0.0

# security:
#   - firebase-auth: []

# components:
#   securitySchemes:
#     firebase-auth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
#       description: "firebase id token"

#   parameters:
#     list-id:
#       - name: list-id
#         in: path
#         schema:
#           type: string
#         required: true

#     list-item-id:
#       - name: list-item-id
#         in: path
#         schema:
#           type: string
#         required: true

#   schemas:
#     list:
#       properties:
#         id:
#           type: string
#         title:
#           type: string
#         description:
#           type: string
#         userIds:
#           type: array
#           items:
#             type: string
#       # examples:
#       #   value:
#       #     {
#       #       "id": "386b2966-121a-413c-8b60-c9ddf4a3bccd",
#       #       "userIds": ["b05121bd-2994-4ba8-b0fe-7e0e112216be"],
#       #       "title": "Scary movies 👻",
#       #       "description": "A collection of the scariest movies I've seen.",
#       #     }

#     list-info:
#       properties:
#         title:
#           type: string
#         description:
#           type: string
#       # examples:
#       #   value:
#       #     {
#       #       "title": "Scary movies 👻",
#       #       "description": "A collection of the scariest movies I've seen.",
#       #     }

#     pagination:
#       properties:
#         page:
#           type: string

# "/lists/{list-id}/items":
#   post:
#     tags:
#       - "Lists"
#     summary: "add a item to a list"

# /lists/{listId}/items/{listItemId}:
#   delete:
#     tags:
#       - "Lists"
#     summary: remove an item from a list
#     parameters:
#       - $ref: "#/components/parameters/list-id"
#       - $ref: "#/components/parameters/list-item-id"

# /lists/{list-id}:
#   get:
#     tags:
#       - "Lists"
#     summary: get a list
#     parameters:
#       - $ref: "#/components/parameters/list-id"

#   delete:
#     tags:
#       - "Lists"
#     summary: "delete a list"
#     parameters:
#       $ref: "#/components/parameters/list-id"

# /lists:
#   get:
#     tags:
#       - "Lists"

#     summary: "get all the lists for a user"

#     parameters:
#       $ref: "#components/parameters/list-id"

#     responses:
#       200:
#         content:
#           application/json:
#             schema:
#               type: array
#               items:
#                 $ref: "#/components/schemas/list"

#   post:
#     tags:
#       - "Lists"
#     summary: create a new list

#     requestBody:
#       content:
#         application/json:
#           schema:
#             $ref: "#/components/schemas/list-info"

#     responses:
#       "201":
#         content:
#           schema:
#             $ref: "#/components/schemas/list"
